---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install tree
    apt:
       name: tree
       state: present
       update_cache: yes
  - name: want to see output response afetr creating file
    debug: 
      msg: "{{myfileoutput}}"