---
- hosts: mydatabseserver
  become: yes
  tasks:
  - name: i want to install apache2
    apt: 
      name: apache2
      state: present
      update_cache: yes
    

  - name: i want to ping
    ping:
    notify: restartWebserver

  - name: i want to install tree
    apt: 
      name: tree
      state: present
    notify: restartWebserver 
  
  handlers:
  - name: restartWebserver
    service: 
      name: apache2
      state: restarted

  

  
  
