--- # tabs dont work for yaml
- hosts : all  # since we need to run on all host
  become : yes   # already user is sudo user so using its sudo privilege
  gather_facts : yes   # yes or no dosent matter it will alweays gather facts
  tasks :
    - name: Install apache httpd  
      apt:
          name: apache2
          state: present
      when: ansible_os_family == "Debian" # will based on the condition only install on debian system
    
    - name : i wan to ping all nodes  
      ping :
    
    - name : installing tree
      apt : 
            name: tree
            state : present
      when : ansible_os_family=='Debian'    # if not used and differenrt os are used then simply failed red lines will be therr
      

    - name : i want to install on redhat apache2
      dnf :
           name : httpd
           state : latest
      when : ansible_os_family=='RedHat'

    - name : i want to install trree on redhat 
      dnf : 
          name : tree
          state: latest
      when : ansible_os_family == 'RedHat'

    - name: Start service httpd, if not started
      ansible.builtin.service:
            name: 
               -httpd
               -apache2
            state: started

         