---
- hosts: mytestingserverPrivate
  become: yes
  tasks: 
  - name: install git 
    apt:
      name: git
      state: present
      update_cache: yes
    tags: mygit

  - name: install apache2
    apt:
      name: apache2
      state: present
      update_cache: yes
    tags: myapache
    when: ansible_os_family == 'Debian'
    